### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by iO2v74XnUfZvhDE** [TeamKun/KPMUpgrader#1]
https://github.com/TeamKun/KPMUpgrader/blob/main/src/main/java/net/kunmc/lab/internalkpm/upgrader/UpgradeImpl.java#L86

**Comment by PeyaPeyaPeyang** [comment]
KPMUpgrader に貢献いただきありがとうございます.
この Issue は, コミット ec4015aee4469d1d7a17cd40ca62d7af67bd25c8 および e8cfb131dc1bd615faa90132124cd3d471f66059 で解決されました.  
また, この問題の修正を含むコミットが, 次のリリース計画に追加されました.

またのご貢献をお待ちしております.
